Repository sensu/web, pull requests merged in 2019-06, with the labels that each got.

#138 Disallow global RegExp instances
  .eslintrc.yml
  config/eslint-plugin/index.js
  config/eslint-plugin/package.json
  package.json
  yarn.lock
Labels: tag: tools, web-ui

#139 Create useQuery React hook
  package.json
  src/lib/component/util/Query.tsx
  src/lib/component/util/index.js
  src/lib/component/util/useApolloClient.tsx
  src/lib/component/util/useQuery.tsx
  yarn.lock
Labels: tag: enhancement, web-ui

#145 Replace named type exports with wildcard export
  src/lib/component/util/QueryParams/index.tsx
  src/lib/component/util/index.tsx
Labels: web-ui

#144 Upgrade apollo-client to latest version and remove deprecated apollo-link-state
  package.json
  src/lib/apollo/client.js
  src/lib/apollo/client.tsx
  src/lib/apollo/httpLink.js
  src/lib/apollo/httpLink.tsx
  src/lib/apollo/introspectionLink.js
  src/lib/apollo/resolvers/auth.js
  src/lib/apollo/stateLink.js
  src/lib/apollo/tokenRefreshLink.js
  src/lib/util/authAPI.js
  src/lib/util/fetch.tsx
  src/vendor/apollo-link-context.tsx
  src/vendor/index.tsx
  yarn.lock
Labels: web-ui

#136 Validate silence's check & subscription fields
  src/lib/component/partial/ClearSilencedEntriesDialog/Dialog.js
  src/lib/component/partial/ConfirmDelete/Dialog.js
  src/lib/component/partial/SilenceEntryDialog.js
  src/lib/component/partial/SilenceEntryForm/SilenceEntryForm.js
  src/lib/component/partial/SilencesList/SilencesListHeader.js
  src/lib/component/partial/ToolbarSelect/Option.js
  src/lib/util/index.tsx
  src/lib/util/validation.js
  src/lib/util/validator.js
  src/lib/util/validator.test.js
Labels: tag: bug fix, web-ui

#151 Update `parseFilter` logic to allow for ":" values
  src/lib/util/filterParams.tsx
Labels: tag: bug fix

#152 Add tests for filter params module
  src/lib/util/filterParams.test.js
Labels: issue: tech debt

#154 Use presence of data as part of heuristic for displaying empty state
  src/lib/component/view/ChecksView.tsx
Labels: tag: bug fix

#155 Adds new view for viewing mutator details
  package.json
  src/app/index.js
  src/lib/apollo/resolvers/deleted.graphql
  src/lib/apollo/stateLink.js
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsConfiguration.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
  src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
  src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsConfiguration.tsx
  src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsContainer.tsx
  src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsToolbar.tsx
  src/lib/component/partial/MutatorDetailsContainer/index.tsx
  src/lib/component/partial/index.js
  src/lib/component/util/useRouter.tsx
  src/lib/component/view/MutatorDetailsView.tsx
  src/lib/component/view/index.js
  src/lib/util/filterParams.test.js
Labels: tag: enhancement, web-ui

#157 Create the Event Filter Details view
  src/app/index.js
  src/lib/apollo/resolvers/deleted.graphql
  src/lib/apollo/stateLink.js
  src/lib/component/base/CodeHighlight/CodeHighlight.js
  src/lib/component/base/CodeHighlight/CodeHighlight.worker.js
  src/lib/component/partial/EntitiesList/EntitiesListHeader.js
  src/lib/component/partial/EventFilterActionLabel/EventFilterActionLabel.tsx
  src/lib/component/partial/EventFilterActionLabel/index.tsx
  src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsConfiguration.tsx
  src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsContainer.tsx
  src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsToolbar.tsx
  src/lib/component/partial/EventFilterDetailsContainer/index.tsx
  src/lib/component/partial/EventFiltersList/EventFiltersListHeader.tsx
  src/lib/component/partial/EventFiltersList/EventFiltersListItem.tsx
  src/lib/component/partial/ListHeader/ListHeader.js
  src/lib/component/partial/index.js
  src/lib/component/view/EventFilterDetailsView.tsx
  src/lib/component/view/EventFiltersView.tsx
  src/lib/component/view/index.js
Labels: web-ui
