Repository sensu/web, pull requests merged in 2019-12, with the labels that each got.

#219 Optionally allow for breadcrumbs to be disabled
  src/lib/apollo/resolvers/auth.js
  src/lib/component/base/AppLayout/AppLayout.js
  src/lib/component/partial/AppLayout.js
Labels: tag: enhancement

#222 Adds check and entity labels to the event details view
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsConfiguration.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsCheckSummary.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsEntitySummary.js
  src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsConfiguration.tsx
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
  src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
  src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsConfiguration.tsx
Labels: tag: bug fix, web-ui

#221 Set offline status when non-500 server errs occur
  src/lib/apollo/httpLink.tsx
  src/lib/component/util/AuthInvalidRoute.js
  src/lib/component/util/NamespaceRoute.js
  src/lib/component/view/CheckDetailsView.tsx
  src/lib/component/view/ChecksView.tsx
  src/lib/component/view/EntitiesView.tsx
  src/lib/component/view/EntityDetailsView.tsx
  src/lib/component/view/EventDetailsView.tsx
  src/lib/component/view/EventFilterDetailsView.tsx
  src/lib/component/view/EventFiltersView.tsx
  src/lib/component/view/EventsView.tsx
  src/lib/component/view/HandlerDetailsView.tsx
  src/lib/component/view/HandlersView.tsx
  src/lib/component/view/MutatorDetailsView.tsx
  src/lib/component/view/MutatorsView.tsx
  src/lib/component/view/SilencesView.tsx
  src/lib/util/fetchError.tsx
  src/lib/util/index.tsx
Labels: tag: enhancement, web-ui
