Repository sensu/web, pull requests merged in 2019-05, with the labels that each got.

#98 Display errors in status toasts
  src/lib/component/base/Toast.js
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsExecuteAction.js
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsPublishAction.js
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsUnpublishAction.js
  src/lib/component/partial/ChecksList/ChecksList.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsReRunAction.js
  src/lib/component/partial/EventsList/EventsList.js
  src/lib/component/relocation/index.js
  src/lib/component/relocation/useBanner.js
  src/lib/component/relocation/usePromiseBoundComponent.js
  src/lib/component/relocation/useToast.js
  src/lib/component/toast/ExecuteCheckStatusToast.js
  src/lib/component/toast/PublishCheckStatusToast.js
  src/lib/component/toast/index.js
  src/lib/error/index.js
Labels: tag: enhancement, web-ui

#105 Prevent non Error instances from breaking the error handler
  src/lib/component/root/ErrorRoot.js
  src/lib/exceptionHandler/index.js
  src/lib/util/error.js
Labels: tag: bug fix, web-ui

#106 Fix broken createSilence mutation error handling logic
  src/lib/mutation/createSilence.js
Labels: tag: bug fix, web-ui

#103 Rework filtering
  package.json
  src/lib/component/base/FilterList/FilterList.js
  src/lib/component/base/FilterList/index.js
  src/lib/component/base/index.js
  src/lib/component/partial/ChecksList/ChecksList.js
  src/lib/component/partial/ChecksList/ChecksListHeader.js
  src/lib/component/partial/ChecksList/ChecksListToolbar.js
  src/lib/component/partial/EntitiesList/EntitiesList.js
  src/lib/component/partial/EntitiesList/EntitiesListHeader.js
  src/lib/component/partial/EntitiesList/EntitiesListToolbar.js
  src/lib/component/partial/EventsList/EventsList.js
  src/lib/component/partial/EventsList/EventsListHeader.js
  src/lib/component/partial/EventsList/EventsListToolbar.js
  src/lib/component/partial/EventsList/StatusMenu.js
  src/lib/component/partial/SilencesList/SilencesList.js
  src/lib/component/partial/SilencesList/SilencesListHeader.js
  src/lib/component/partial/SilencesList/SilencesListToolbar.js
  src/lib/component/partial/ToolbarSelect/Option.js
  src/lib/component/util/QueryParams/QueryParams.js
  src/lib/component/view/ChecksView.js
  src/lib/component/view/EntitiesView.js
  src/lib/component/view/EventsView.js
  src/lib/component/view/SilencesView.js
  src/lib/util/array.js
  src/lib/util/filterParams.js
  src/lib/util/index.js
Labels: tag: enhancement, web-ui

#108 Allow users to view a collection of Handlers
  src/app/index.js
  src/lib/component/icon/index.js
  src/lib/component/partial/HandlersList/HandlersList.js
  src/lib/component/partial/HandlersList/HandlersListHeader.js
  src/lib/component/partial/HandlersList/HandlersListItem.js
  src/lib/component/partial/HandlersList/HandlersListItemDetails.js
  src/lib/component/partial/HandlersList/HandlersListToolbar.js
  src/lib/component/partial/HandlersList/index.js
  src/lib/component/partial/index.js
  src/lib/component/view/HandlersView.js
  src/lib/component/view/index.js
Labels: tag: enhancement, web-ui

#109 Allow users to view the configuration of an individual Handler
  src/app/index.js
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsContainer.js
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsToolbar.js
  src/lib/component/partial/HandlerDetailsContainer/index.js
  src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
  src/lib/component/partial/index.js
  src/lib/component/view/HandlerDetailsView.js
  src/lib/component/view/index.js
Labels: tag: enhancement, web-ui

#115 Include `id` field when querying handlers
  src/lib/component/view/HandlerDetailsView.js
Labels: web-ui

#119 [Bugfix] Properly display handler timeout
  src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
Labels: tag: bug fix

#122 Hide scroll bars from CodeBlock elements
  src/lib/component/base/CodeBlock/CodeBlock.js
Labels: tag: bug fix

#117 Support non-standard and invalid cron expressions
  src/lib/component/partial/CronDescriptor/CronDescriptor.js
  src/lib/util/cron.js
  src/lib/util/cron.test.js
  src/lib/util/date.js
  src/lib/util/date.test.js
  src/lib/util/index.js
Labels: tag: bug fix, web-ui

#133 Avoid blindly sending user to 'default' namespace
  src/lib/apollo/resolvers/lastNamespace.graphql
  src/lib/apollo/resolvers/lastNamespace.js
Labels: tag: bug fix, web-ui

#134 Avoid exception when submitting empty SignIn form
  src/lib/component/partial/SigninDialog/SigninForm.js
Labels: tag: bug fix, web-ui

#137 Make upload-artifacts script configurable
  scripts/upload-artifacts.js
Labels: tag: tools, web-ui

#124 Re-add ability to delete entities
  src/lib/component/partial/EntitiesList/EntitiesList.js
  src/lib/component/partial/EntitiesList/EntitiesListHeader.js
  src/lib/component/partial/EntitiesList/EntitiesListItem.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsDeleteAction.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsToolbar.js
  src/lib/mutation/deleteEntity.js
  src/lib/mutation/index.js
Labels: tag: enhancement, web-ui
