Repository sensu/web, pull requests merged in 2019-07, with the labels that each got.

#160 [Bug] Disable re-run action for proxy entity checks
  src/lib/component/partial/EventDetailsContainer/EventDetailsReRunAction.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsToolbar.js
Labels: tag: bug fix

#168 Bump mixin-deep & set-value dependencies
  yarn.lock
Labels: dependencies

#165 Namespaces with hyphen are inline in drawer
  src/lib/component/partial/Drawer.js
  src/lib/component/partial/NamespaceLabel/NamespaceLabelBase.js
  src/lib/component/partial/NamespaceSelector/NamespaceSelectorBuilder.js
Labels: web-ui

#172 Handle rejected result; fix refresh token crash
  src/lib/component/util/AuthInvalidRoute.js
  src/lib/component/util/useQuery.tsx
Labels: tag: bug fix, web-ui
