Repository sensu/web, pull requests merged in 2019-04, with the labels that each got.

#52 Omit entity subscription when re-running check for proxy entity
  src/app/component/partial/EventDetailsContainer/EventDetailsReRunAction.js
  src/app/component/partial/EventsList/EventsList.js
Labels: tag: bug fix

#61 Query details using given query param
  src/lib/component/view/CheckDetailsView.js
  src/lib/component/view/EntityDetailsView.js
Labels: tag: bug fix

#63 Fix broken imports in ToolbarSelect/Option component
  src/lib/component/partial/ToolbarSelect/Option.js
Labels: tag: bug fix

#64 Add toolbarItems callback prop to view components
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsContainer.js
  src/lib/component/partial/CheckDetailsContainer/CheckDetailsToolbar.js
  src/lib/component/partial/ChecksList/ChecksListHeader.js
  src/lib/component/partial/ChecksList/ChecksListItem.js
  src/lib/component/partial/ChecksList/ChecksListToolbar.js
  src/lib/component/partial/EntitiesList/EntitiesListHeader.js
  src/lib/component/partial/EntitiesList/EntitiesListItem.js
  src/lib/component/partial/EntitiesList/EntitiesListToolbar.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsContainer.js
  src/lib/component/partial/EntityDetailsContainer/EntityDetailsToolbar.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsContent.js
  src/lib/component/partial/EventDetailsContainer/EventDetailsToolbar.js
  src/lib/component/partial/EventsList/EventsListHeader.js
  src/lib/component/partial/EventsList/EventsListItem.js
  src/lib/component/partial/EventsList/EventsListToolbar.js
  src/lib/component/partial/QuickNav/Nav.js
  src/lib/component/partial/SilencesList/SilencesListHeader.js
  src/lib/component/partial/SilencesList/SilencesListItem.js
  src/lib/component/partial/SilencesList/SilencesListToolbar.js
  src/lib/component/partial/ToolbarMenu/Item.js
  src/lib/component/partial/ToolbarMenu/ToolbarMenu.js
  src/lib/component/partial/ToolbarMenu/index.js
  src/lib/component/view/CheckDetailsView.js
  src/lib/component/view/ChecksView.js
  src/lib/component/view/EntitiesView.js
  src/lib/component/view/EntityDetailsView.js
  src/lib/component/view/EventDetailsView.js
  src/lib/component/view/EventsView.js
  src/lib/component/view/SilencesView.js
Labels: tag: enhancement

#65 Downgrade apollo-client
  package.json
  src/lib/apollo/client.js
  src/lib/apollo/stateLink.js
  yarn.lock
Labels: tag: bug fix

#67 Upgrade react to latest version
  package.json
  yarn.lock
Labels: tag: enhancement

#66 Add app initializer step to update service workers
  src/app/index.js
  src/lib/util/index.js
  src/lib/util/serviceWorker.js
Labels: tag: bug fix

#70 Update packages failing audit
  package.json
  yarn.lock
Labels: tag: tools

#71 Update halting error modal with collapsible details
  package.json
  src/lib/buildInfo.js
  src/lib/buildInfo.macro.js
  src/lib/component/base/ErrorDialog/ErrorDialog.js
  src/lib/component/base/ErrorDialog/index.js
  src/lib/component/base/index.js
  src/lib/component/root/ErrorRoot.js
  src/lib/component/util/index.js
  src/lib/component/util/useBuildInfo.js
  src/lib/exceptionHandler/index.js
  src/lib/index.js
  src/lib/util/buildInfo.js
  src/lib/util/buildInfo.macro.js
  src/lib/util/error.js
  src/lib/util/index.js
  yarn.lock
Labels: tag: enhancement

#76 Remove re-export of unexported keyword
  src/vendor/react-spring.js
Labels: tag: bug fix

#75 Use key to reference toolbar item instead of removed id prop
  src/lib/component/partial/ToolbarMenu/Partitioner.js
Labels: tag: bug fix

#83 Include id field when checks, entities and events
  src/lib/component/view/CheckDetailsView.js
  src/lib/component/view/EntityDetailsView.js
  src/lib/component/view/EventDetailsView.js
Labels: issue: bug
