Repository sensu/web, pull requests merged in 2020-04, with the labels that each got.

#281 Ensure handlers view filters appear selected
  src/lib/component/partial/HandlersList/HandlersList.js
  src/lib/component/view/HandlersView.tsx
Labels: tag: bug fix

#286 Allows last viewed cluster to be persisted
  src/lib/apollo/client.tsx
  src/lib/apollo/resolvers/lastNamespace.graphql
  src/lib/apollo/resolvers/lastNamespace.js
Labels: tag: enhancement

#287 Adds global configurable page size and theme preference
  src/app/index.js
  src/lib/apollo/resolvers/theme.js
  src/lib/component/base/AppThemeProvider.tsx
  src/lib/component/partial/Preferences.js
  src/lib/component/util/ConfigurationProvider/context.tsx
  src/lib/component/util/index.tsx
  src/lib/component/util/usePreferredTheme.tsx
  src/lib/component/view/ChecksView.tsx
  src/lib/component/view/EntitiesView.tsx
  src/lib/component/view/EventFiltersView.tsx
  src/lib/component/view/EventsView.tsx
  src/lib/component/view/HandlersView.tsx
  src/lib/component/view/MutatorsView.tsx
  src/lib/component/view/SilencesView.tsx
  src/lib/constant/configuration.tsx
  src/lib/constant/index.tsx
Labels: tag: enhancement

#288 Use web config for displaying image labels
  package.json
  src/lib/component/partial/KeyValueChip/KeyValueChip.stories.js
  src/lib/component/partial/KeyValueChip/KeyValueChip.tsx
  src/lib/component/util/AutoLink.tsx
  src/lib/util/index.tsx
  src/lib/util/linkPolicy.test.ts
  src/lib/util/linkPolicy.ts
  src/lib/util/url.ts
  yarn.lock
Labels: tag: enhancement, web-ui

#292 Fix issue where default theme was misconfigured
  src/lib/component/base/ThemeProvider.js
  src/lib/constant/configuration.tsx
Labels: tag: bug fix

#291 Increase font-weight for headers
  src/lib/theme/defaults.js
Labels: tag: enhancement
