Repository sensu/web, pull requests merged in 2020-09, with the labels that each got.

#337 Installation Instructions and Prod-Friendly Running
  INSTALL.md
  README.md
  scripts/serve.js
Labels: component:web-ui

#339 Bump http-proxy dependency
  package.json
  scripts/serve.js
  src/lib/component/partial/ContextSwitcher/ContextSwitcher.tsx
  yarn.lock
Labels: component:web-ui, tag: tools

#340 Pull relevant bugfixes from upstream project
  src/app/apollo/resolvers/auth.js
  src/lib/component/partial/Pagination.js
  src/lib/component/partial/Pagination.stories.js
  src/lib/component/partial/Pagination.tsx
Labels: component:web-ui, tag: bug fix
