Repository sensu/web, pull requests merged in 2020-03, with the labels that each got.

#257 Ensure height value is applied to banner
  src/lib/component/base/Drawer/Drawer.tsx
  src/lib/component/relocation/BannerWell.js
  src/lib/component/relocation/BannerWell.tsx
  src/lib/component/relocation/ToastWell.js
  src/lib/component/relocation/ToastWell.tsx
  src/lib/theme/classic.js
  src/lib/theme/sensu.js
Labels: tag: bug fix, web-ui

#258 Big fixes for some preset filters issues
  src/lib/component/partial/ChecksList/ChecksListHeader.js
  src/lib/component/partial/EntitiesList/EntitiesListHeader.js
  src/lib/component/partial/EventFiltersList/EventFiltersListHeader.tsx
  src/lib/component/partial/EventsList/EventsListHeader.js
  src/lib/component/partial/EventsList/StatusMenu.js
  src/lib/component/partial/HandlersList/HandlersListHeader.js
  src/lib/component/partial/ListSortSelector/ListSortSelector.js
  src/lib/component/partial/ListSortSelector/ListSortSelectorMenu.js
  src/lib/component/partial/SilencesList/SilencesListHeader.js
  src/lib/component/partial/ToolbarMenuItems/Select.js
  src/lib/component/partial/ToolbarSelect/Controller.js
  src/lib/component/partial/ToolbarSelect/None.js
  src/lib/component/partial/ToolbarSelect/Select.js
Labels: tag: bug fix, web-ui

#259 Ensure page & page size are not lost while paginating
  src/lib/component/partial/HandlersList/HandlersList.js
  src/lib/component/partial/MutatorsList/MutatorsList.js
  src/lib/component/partial/SilencesList/SilencesList.js
Labels: tag: bug fix, web-ui

#260 Fix overlapping switcher headings in FF
  src/lib/component/partial/ContextSwitcher/ContextSwitcherListHeader.tsx
Labels: tag: bug fix, web-ui

#263 use topBarHeight to set Drawer's top position
  src/lib/component/base/Drawer/Drawer.tsx
Labels: tag: bug fix, web-ui

#238 Add images to labels
  src/lib/component/partial/KeyValueChip/KeyValueChip.js
Labels: tag: enhancement, web-ui

#269 Fix font colour issues with the "classic" theme
  src/lib/colors/pistachio.js
  src/lib/theme/classic.js
Labels: tag: bug fix

#270 Convert confirm delete component to Typescript
  src/lib/component/partial/ConfirmDelete/Confirm.js
  src/lib/component/partial/ConfirmDelete/Confirm.tsx
  src/lib/component/partial/ConfirmDelete/index.tsx
  src/lib/component/util/ConfirmAction.js
  src/lib/component/util/ConfirmAction.tsx
Labels: tag: enhancement, web-ui

#272 Adds an active state to drawer items
  src/lib/component/base/Drawer/MenuItem.tsx
  yarn.lock
Labels: tag: enhancement, web-ui

#60 Add two themes for colour blindness
  .storybook/theme.js
  src/lib/colors/blue.js
  src/lib/colors/green.js
  src/lib/colors/index.js
  src/lib/colors/indigo.js
  src/lib/colors/lime.js
  src/lib/colors/paynesGrey.js
  src/lib/colors/pink.js
  src/lib/colors/red.js
  src/lib/colors/redderRed.js
  src/lib/colors/teal.js
  src/lib/colors/yellow.js
  src/lib/component/base/Banner/Banner.js
  src/lib/component/base/Toast/Toast.js
  src/lib/component/partial/Preferences.js
  src/lib/theme/defaults.js
  src/lib/theme/deuteranopia.js
  src/lib/theme/index.js
  src/lib/theme/sensu.js
  src/lib/theme/tritanopia.js
  src/lib/theme/uchiwa.js
Labels: tag: enhancement

#274 fixup alignment of switches in Preferences pane
  src/lib/component/partial/Preferences.js
Labels: tag: bug fix, web-ui

#275 Keep folders open when child link is active
  src/lib/component/base/Drawer/MenuItem.tsx
Labels: tag: enhancement, web-ui

#276 Fix styling of the 404 page
  src/lib/component/base/Lizy.tsx
  src/lib/component/base/index.tsx
  src/lib/component/partial/NotFound.js
  src/lib/component/view/NamespaceNotFoundView.js
Labels: tag: bug fix, web-ui

#277 avoid using active state for menu items without link
  src/lib/component/base/Drawer/MenuItem.tsx
Labels: tag: bug fix, web-ui

#278 Fix Crash with Image Labels
  src/lib/component/partial/KeyValueChip/KeyValueChip.js
  src/lib/component/partial/KeyValueChip/KeyValueChip.tsx
Labels: web-ui

#280 Ensures labels and annotations are clickable
  src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js
  src/lib/component/partial/KeyValueChip/KeyValueChip.tsx
Labels: tag: bug fix

#283 Avoid null references in Well components
  src/lib/component/relocation/BannerWell.tsx
  src/lib/component/relocation/ToastWell.tsx
Labels: tag: bug fix
